-- MySQL Script generated by MySQL Workbench
-- Sun May 29 15:45:16 2022
-- Model: crash_sql    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 31300146_niecko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 31300146_niecko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `31300146_niecko` DEFAULT CHARACTER SET utf8 ;
USE `31300146_niecko` ;

-- -----------------------------------------------------
-- Table `31300146_niecko`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`images` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `alt` VARCHAR(255) NOT NULL DEFAULT 'placeholder image',
  `path` VARCHAR(255) NOT NULL DEFAULT '/crash/public/img/placeholder.jpg',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_image`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `kudos` INT NULL DEFAULT 0,
  `administrator` TINYINT UNSIGNED NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `images_id_image` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  INDEX `fk_users_images1_idx` (`images_id_image` ASC) ,
  CONSTRAINT `fk_users_images1`
    FOREIGN KEY (`images_id_image`)
    REFERENCES `31300146_niecko`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `31300146_niecko`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`sessions` (
  `id_session` INT NOT NULL AUTO_INCREMENT,
  `secret` VARCHAR(45) NOT NULL,
  `users_id_user` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_session`),
  INDEX `fk_sessions_users1_idx` (`users_id_user` ASC) ,
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `31300146_niecko`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `31300146_niecko`.`images`
-- -----------------------------------------------------
START TRANSACTION;
USE `31300146_niecko`;
INSERT INTO `31300146_niecko`.`images` (`id_image`, `alt`, `path`, `created_at`, `updated_at`) VALUES (1, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `31300146_niecko`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `31300146_niecko`;
INSERT INTO `31300146_niecko`.`users` (`id_user`, `username`, `password`, `kudos`, `administrator`, `created_at`, `updated_at`, `images_id_image`) VALUES (1, 'admin', '$2y$10$SAh6W2V5.h8/TMGWyBYRheSUyyWvLMDhc8yuNI1NEerFCNf7a4mvK', 0, 1, DEFAULT, DEFAULT, DEFAULT);

COMMIT;

