-- MySQL Script generated by MySQL Workbench
-- Fri May 20 12:40:41 2022
-- Model: crash_sql    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 31300146_niecko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 31300146_niecko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `31300146_niecko` DEFAULT CHARACTER SET utf8 ;
USE `31300146_niecko` ;

-- -----------------------------------------------------
-- Table `31300146_niecko`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`images` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `alt` VARCHAR(255) NOT NULL DEFAULT 'placeholder image',
  `path` VARCHAR(255) NOT NULL DEFAULT '/crash/public/img/placeholder.jpg',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_image`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `administrator` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `images_id_image` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_users_images1_idx` (`images_id_image` ASC),
  CONSTRAINT `fk_users_images1`
    FOREIGN KEY (`images_id_image`)
    REFERENCES `31300146_niecko`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `31300146_niecko`.`fandoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`fandoms` (
  `id_fandom` INT NOT NULL AUTO_INCREMENT,
  `friendly_name` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_fandom`),
  UNIQUE INDEX `friendly_name_UNIQUE` (`friendly_name` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`publications` (
  `id_publication` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(65) NOT NULL DEFAULT 'Untitled',
  `planned_length` INT NOT NULL DEFAULT 0,
  `status` TINYINT NULL,
  `url` VARCHAR(255) NOT NULL,
  `prompt` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id_user` INT NOT NULL,
  `fandoms_id_fandom` INT NOT NULL,
  `images_id_image` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_publication`, `users_id_user`, `fandoms_id_fandom`),
  INDEX `fk_publications_users1_idx` (`users_id_user` ASC),
  INDEX `fk_publications_fandoms1_idx` (`fandoms_id_fandom` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  INDEX `fk_publications_images1_idx` (`images_id_image` ASC),
  CONSTRAINT `fk_publications_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `31300146_niecko`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publications_fandoms1`
    FOREIGN KEY (`fandoms_id_fandom`)
    REFERENCES `31300146_niecko`.`fandoms` (`id_fandom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publications_images1`
    FOREIGN KEY (`images_id_image`)
    REFERENCES `31300146_niecko`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`tags` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `friendly_name` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tag`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`sessions` (
  `id_session` INT NOT NULL AUTO_INCREMENT,
  `secret` VARCHAR(45) NOT NULL,
  `users_id_user` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_session`),
  INDEX `fk_sessions_users1_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `31300146_niecko`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`pages` (
  `id_page` INT NOT NULL AUTO_INCREMENT,
  `friendly_name` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `content` TEXT NULL,
  `custom_css` TEXT NULL,
  `javascript` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_page`),
  UNIQUE INDEX `id_page_UNIQUE` (`id_page` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`heads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`heads` (
  `id_head` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NULL,
  `desc` VARCHAR(160) NULL,
  `pages_id_page` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_head`, `pages_id_page`),
  INDEX `fk_heads_pages1_idx` (`pages_id_page` ASC),
  CONSTRAINT `fk_heads_pages1`
    FOREIGN KEY (`pages_id_page`)
    REFERENCES `31300146_niecko`.`pages` (`id_page`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`leafs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`leafs` (
  `id_leaf` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL DEFAULT 'Untitled',
  `body` TEXT NOT NULL,
  `word_count` INT NOT NULL DEFAULT 0,
  `publications_id_publication` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_leaf`, `publications_id_publication`),
  INDEX `fk_leafs_publications1_idx` (`publications_id_publication` ASC),
  CONSTRAINT `fk_leafs_publications1`
    FOREIGN KEY (`publications_id_publication`)
    REFERENCES `31300146_niecko`.`publications` (`id_publication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`tags_has_publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`tags_has_publications` (
  `tags_id_tag` INT NOT NULL,
  `publications_id_publication` INT NOT NULL,
  PRIMARY KEY (`tags_id_tag`, `publications_id_publication`),
  INDEX `fk_tags_has_publications_publications1_idx` (`publications_id_publication` ASC),
  INDEX `fk_tags_has_publications_tags1_idx` (`tags_id_tag` ASC),
  CONSTRAINT `fk_tags_has_publications_tags1`
    FOREIGN KEY (`tags_id_tag`)
    REFERENCES `31300146_niecko`.`tags` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_has_publications_publications1`
    FOREIGN KEY (`publications_id_publication`)
    REFERENCES `31300146_niecko`.`publications` (`id_publication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`kudos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`kudos` (
  `users_id_user` INT NOT NULL,
  `publications_id_publication` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`users_id_user`, `publications_id_publication`),
  INDEX `fk_users_has_publications_publications1_idx` (`publications_id_publication` ASC),
  INDEX `fk_users_has_publications_users1_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_users_has_publications_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `31300146_niecko`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_publications_publications1`
    FOREIGN KEY (`publications_id_publication`)
    REFERENCES `31300146_niecko`.`publications` (`id_publication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `31300146_niecko`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`comments` (
  `id_comment` INT NOT NULL,
  `users_id_user` INT NOT NULL,
  `publications_id_publication` INT NOT NULL,
  `body` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_comment`, `users_id_user`, `publications_id_publication`),
  INDEX `fk_comment_users1_idx` (`users_id_user` ASC),
  INDEX `fk_comment_publications1_idx` (`publications_id_publication` ASC),
  CONSTRAINT `fk_comment_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `31300146_niecko`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_publications1`
    FOREIGN KEY (`publications_id_publication`)
    REFERENCES `31300146_niecko`.`publications` (`id_publication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `31300146_niecko`.`images`
-- -----------------------------------------------------
START TRANSACTION;
USE `31300146_niecko`;
INSERT INTO `31300146_niecko`.`images` (`id_image`, `alt`, `path`, `created_at`, `updated_at`) VALUES (1, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `31300146_niecko`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `31300146_niecko`;
INSERT INTO `31300146_niecko`.`users` (`id_user`, `username`, `password`, `active`, `administrator`, `created_at`, `updated_at`, `images_id_image`) VALUES (1, 'admin', '$2y$10$SAh6W2V5.h8/TMGWyBYRheSUyyWvLMDhc8yuNI1NEerFCNf7a4mvK', 0, 1, DEFAULT, DEFAULT, DEFAULT);

COMMIT;

