-- MySQL Script generated by MySQL Workbench
-- Fri Apr 15 12:33:33 2022
-- Model: crash_sql    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 31300146_niecko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 31300146_niecko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `31300146_niecko` DEFAULT CHARACTER SET utf8 ;
USE `31300146_niecko` ;

-- -----------------------------------------------------
-- Table `31300146_niecko`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(34) NOT NULL,
  `kudos` INT NULL DEFAULT 0,
  `avatar` VARCHAR(255) NULL DEFAULT 'storage/img/avi_placeholder.jpg',
  `administrator` TINYINT UNSIGNED NULL DEFAULT 0,
  `time_stamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`));


-- -----------------------------------------------------
-- Table `31300146_niecko`.`fandoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`fandoms` (
  `id_fandom` INT NOT NULL AUTO_INCREMENT,
  `friendly_name` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_fandom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`publications` (
  `id_publication` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(65) NULL DEFAULT 'Untitled',
  `body` LONGTEXT NOT NULL,
  `planned_length` INT NULL DEFAULT 0,
  `status` TINYINT NULL,
  `time_stamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id_user` INT NOT NULL,
  `fandoms_id_fandom` INT NOT NULL,
  PRIMARY KEY (`id_publication`, `users_id_user`, `fandoms_id_fandom`),
  INDEX `fk_publications_users1_idx` (`users_id_user` ASC),
  INDEX `fk_publications_fandoms1_idx` (`fandoms_id_fandom` ASC),
  CONSTRAINT `fk_publications_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `31300146_niecko`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publications_fandoms1`
    FOREIGN KEY (`fandoms_id_fandom`)
    REFERENCES `31300146_niecko`.`fandoms` (`id_fandom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`tags` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `friendly_name` VARCHAR(100) NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`sessions` (
  `id_session` INT NOT NULL AUTO_INCREMENT,
  `secret` VARCHAR(45) NOT NULL,
  `users_id_user` INT NOT NULL,
  PRIMARY KEY (`id_session`),
  INDEX `fk_sessions_users1_idx` (`users_id_user` ASC) ,
  CONSTRAINT `fk_sessions_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `31300146_niecko`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`leafs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`leafs` (
  `id_leaf` INT NOT NULL AUTO_INCREMENT,
  `body` LONGTEXT NOT NULL,
  `publications_id_publication` INT NOT NULL,
  PRIMARY KEY (`id_leaf`, `publications_id_publication`),
  INDEX `fk_leafs_publications1_idx` (`publications_id_publication` ASC) ,
  CONSTRAINT `fk_leafs_publications1`
    FOREIGN KEY (`publications_id_publication`)
    REFERENCES `31300146_niecko`.`publications` (`id_publication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`splasharts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`splasharts` (
  `id_splashart` INT NOT NULL AUTO_INCREMENT,
  `alt` VARCHAR(255) NULL DEFAULT 'publication splashart',
  `path` VARCHAR(255) NULL DEFAULT 'storage/img/splash_placeholder.jpg',
  `leafs_id_leaf` INT NOT NULL,
  `leafs_publications_id_publication` INT NOT NULL,
  PRIMARY KEY (`id_splashart`, `leafs_id_leaf`, `leafs_publications_id_publication`),
  INDEX `fk_splasharts_leafs1_idx` (`leafs_id_leaf` ASC, `leafs_publications_id_publication` ASC) ,
  CONSTRAINT `fk_splasharts_leafs1`
    FOREIGN KEY (`leafs_id_leaf` , `leafs_publications_id_publication`)
    REFERENCES `31300146_niecko`.`leafs` (`id_leaf` , `publications_id_publication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`pages` (
  `id_page` INT NOT NULL AUTO_INCREMENT,
  `friendly_name` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`id_page`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`heads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`heads` (
  `id_head` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NULL,
  `desc` VARCHAR(160) NULL,
  `pages_id_page` INT NOT NULL,
  PRIMARY KEY (`id_head`, `pages_id_page`),
  INDEX `fk_heads_pages1_idx` (`pages_id_page` ASC) ,
  CONSTRAINT `fk_heads_pages1`
    FOREIGN KEY (`pages_id_page`)
    REFERENCES `31300146_niecko`.`pages` (`id_page`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `31300146_niecko`.`tags_has_publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `31300146_niecko`.`tags_has_publications` (
  `tags_id_tag` INT NOT NULL,
  `publications_id_publication` INT NOT NULL,
  PRIMARY KEY (`tags_id_tag`, `publications_id_publication`),
  INDEX `fk_tags_has_publications_publications1_idx` (`publications_id_publication` ASC) ,
  INDEX `fk_tags_has_publications_tags1_idx` (`tags_id_tag` ASC) ,
  CONSTRAINT `fk_tags_has_publications_tags1`
    FOREIGN KEY (`tags_id_tag`)
    REFERENCES `31300146_niecko`.`tags` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_has_publications_publications1`
    FOREIGN KEY (`publications_id_publication`)
    REFERENCES `31300146_niecko`.`publications` (`id_publication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
